sequenceDiagram
    Usuario->>WebApp: Ingresa mensaje o habla
    WebApp->>Cognito: Solicita credenciales temporales
    Cognito-->>WebApp: Credenciales seguras
    WebApp->>LexV2: RecognizeText(text, sessionId)
    LexV2->>Lambda: Fulfillment (slot, intent)
    Lambda->>DynamoDB: get/put cita
    DynamoDB-->>Lambda: Datos
    Lambda-->>LexV2: Respuesta de texto
    LexV2-->>WebApp: Texto respuesta
    WebApp->>Polly: SynthesizeSpeech(text)
    Polly-->>WebApp: Audio MP3
    WebApp->>Usuario: Respuesta hablada + texto